CREATE TABLE IF NOT EXISTS formula
(id INTEGER PRIMARY KEY AUTO_INCREMENT,
 formula VARCHAR(500)) ;

CREATE TABLE IF NOT EXISTS assumption
(id INTEGER PRIMARY KEY AUTO_INCREMENT,
 formula_id INTEGER ,
 goal_id INTEGER);

CREATE TABLE IF NOT EXISTS goal
(id INTEGER PRIMARY KEY AUTO_INCREMENT,
 goal_formula_id INTEGER,
 proof_id INTEGER);

CREATE TABLE IF NOT EXISTS premise
(id INTEGER PRIMARY KEY AUTO_INCREMENT,
 formula_id INTEGER, 
 proof_id INTEGER);

CREATE TABLE IF NOT EXISTS proof
(id INTEGER PRIMARY KEY AUTO_INCREMENT,
 main_goal_id INTEGER); 
 
